---
title: "ITS_analysis"
author: "Tobias"
date: "2024-05-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#this sets wd to root dir
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())


# read in packages
if(!requireNamespace("BiocManager")){
  install.packages("BiocManager")
}

if(!requireNamespace("phyloseq")){
  install.packages("phyloseq")
}

library(phyloseq); packageVersion("phyloseq")
library(tidyverse)


```


```{r read in data}
ps <- readRDS("input/processed_sequences/ITS/ps_ITS.rds")
  
  
  
```



File for exploring and analyzing ITS sequences. These were processed through DADA2 pipeline and saved as a phyloseq object

```{r richness plot}



# plot richness
plot_richness(ps, x="treatment", measures=c("Shannon", "Simpson"), color="day")

```

```{r NMDS}

# make an NMDS

ps.prop <- transform_sample_counts(ps, function(otu) otu/sum(otu))
ord.nmds.bray <- ordinate(ps.prop, method="NMDS", distance="bray")


plot_ordination(ps.prop, ord.nmds.bray, color="treatment", title="Bray NMDS")

```

```{r bar chart}


# make bar chart

top20 <- names(sort(taxa_sums(ps), decreasing=TRUE))[1:20]
ps.top20 <- transform_sample_counts(ps, function(OTU) OTU/sum(OTU))
ps.top20 <- prune_taxa(top20, ps.top20)
plot_bar(ps.top20, x="treatment", fill="Family") + facet_wrap(~day, scales="free_x")



```


```{r contaminants}
asv_tab <- read.csv("input/its/asv_counts_its.csv")

#set column 1 to row names
asv_tab<- asv_tab %>%
  `row.names<-`(., NULL) %>% 
   column_to_rownames(var = "X")


asv_tax <- read.csv("input/its/asv_taxonomy_its.csv")

#set column 1 to row names
asv_tax<- asv_tax %>%
  `row.names<-`(., NULL) %>% 
   column_to_rownames(var = "X")


# create vector saying which samples are controls
vector_for_decontam <- c(rep(TRUE, 1), rep(FALSE, 30))

contam_df <- isContaminant(t(asv_tab), neg=vector_for_decontam)

table(contam_df$contaminant) # identified 6 as contaminants

# getting vector holding the identified contaminant IDs
contam_asvs <- row.names(contam_df[contam_df$contaminant == TRUE, ])

# in this case its 2 taxa
asv_tax[row.names(asv_tax) %in% contam_asvs, ]

```
1 contaminant was found - an unidentified fungi


