---
title: "main_analysis"
author: "Tobias"
date: "2023-06-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#this sets wd to root dir
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())


library(tidyverse) # for data playing
library(rstatix) # for piped stats

# for survival analysis
library(survival)
library(ranger)
library(ggfortify)
library(survminer)
library(coxme)
library(survival)
library(gtsummary)

```

## 2023 osmia bioassay 


```{r data}

df <- read_csv("input/2023_bioassay_datasheets_combined.csv", skip_empty_rows = TRUE)%>%
  filter(!end_date == "remove")%>%
  mutate(end_date = as.Date(end_date, format= "%Y/%m/%d"),
         start_date= as.Date(start_date, format= "%Y/%m/%d"), # make date a date
         status = if_else(end_status == "dead", 1, 0))%>% # add 0 and 1 status for survival analysis
  mutate_if(is.character, factor)%>% # change other chr to factors
    mutate( # make a column of treatment names with line breaks for better graph labels
      splits = if_else( 
        str_count(treatment, '\\S+') > 2,
        str_c(word(treatment,1,1), word(treatment,2,str_count(treatment,'\\S+')), sep = '\n'),
        treatment
      )
    ) %>%
  mutate(days_to_event = end_date-start_date) %>% # calculate the days in assay until cocoon or death
  mutate(treatment=relevel(treatment,ref="Osmia pollen (control)")) %>% # make osmia control first level 
  mutate(day = as.factor(day),
         plate_num = as.factor(plate_num))%>%
  mutate(days_to_death = if_else(end_status == "dead", days_to_event, max(days_to_event))) # i need to make a column where survivors live until the last check point, not just to cocoon
 
head(df)

```
metadata :
  - 



now lets just make a quick summary of 
``` {r summary graph}

prop_death <- df %>%
  ggplot()+
  geom_bar(aes(x=treatment, fill=end_status), position = "fill")+
  ggtitle("break down of death")+
  scale_x_discrete(guide = guide_axis(angle = 0),labels = function(x) str_wrap(x, width = 7))+
  scale_fill_manual(values=c("lightblue4", "red4"))
prop_death


# how long it took each treatment to die
time_to_death <- df %>%
  filter(end_status == "dead") %>%
  ggplot(aes(x=splits, y = days_to_event, color = splits))+
  geom_point()+
  geom_boxplot()

# how long it took each treatment to cocoon
time_to_cocoon <- df %>%
  filter(end_status == "cocoon") %>%
  ggplot(aes(x=splits, y = days_to_event, color = splits))+
  geom_point()+
  geom_boxplot()

```
```{r time of development}

only_control<-df %>%
  filter(end_status=="cocoon", treatment=="Osmia pollen (control)")%>%
  rename(control=treatment)


df %>%
  filter(end_status=="cocoon")%>%
  ggplot(aes(x=days_to_event))+
  geom_density(aes(fill=treatment), alpha=.4)+
  geom_density(data=only_control, aes(fill=control), alpha =.2)+
  facet_wrap(~treatment)+
  guides(fill="none")
```
This is a density graph showing the time until cocoon completion (only showing bees that survived). The development time of control bees is overlayed onto each other treatment.


``` {r kruskal wallis}

df %>%
  kruskal_test(end_status ~ treatment)


df %>%
  dunn_test(end_status ~ treatment, p.adjust.method = "holm")

```



no difference in survival across sex
```{r survival analysis KM}
km_sex <- survfit(Surv(days_to_death, status) ~ sex, data=df)
ggsurvplot(km_sex, data = df, pval = TRUE)



km_day <- survfit(Surv(days_to_death, status) ~ day, data=df)
ggsurvplot(km_day, data = df, pval = TRUE)




km_treatment <- survfit(Surv(days_to_death, status) ~ treatment, data=df)
summary(km_treatment, times = c(1,5*(1:12)))

gg<-ggsurvplot(km_treatment, data = df, pval = TRUE,
           legend = "right",
           conf.int = TRUE,
           conf.int.style = "step",
           conf.int.alpha = .09,
           surv.median.line = "hv")

  if(nudge){
    # this mess puls apart the ggplot/ggsuv object and manually manipulates the values to avoid overlap at the 100% survival line. 
# Jitter ammount is computed using the numeric factor level of the color used for grouping.  Not elegant, but it works in my limited testing.
    gg_decon <- ggplot_build(gg$plot)
    ng <- length(unique(gg_decon$data[[1]]$colour))
   # modify the lines 
    gg_decon$data[[1]] <-  gg_decon$data[[1]] %>%
      mutate(y=ifelse(y==1, 1 + (.01*as.numeric(as.factor(colour))), y))
   # modify the censor point
    gg_decon$data[[3]] <-  gg_decon$data[[3]] %>%
      mutate(y=ifelse(y==1, 1 + (.01*as.numeric(as.factor(colour))), y))
   # from https://ggplot2-book.org/internals.html
    gtable <- ggplot_gtable(gg_decon)
    grid::grid.newpage()
    grid::grid.draw(gtable)
    return(invisible(gtable))
  } else{
    return(gg)
  }



pairwise_survdiff(Surv(days_to_death, status) ~ treatment, data=df, p.adjust.method = "BH", rho = 0)


```


```{r survival cox}


  coxph(Surv(days_to_death, status) ~ treatment, data = df) %>% 
    tbl_regression(exp = TRUE) 

```


```{r cox split by variable}
aa_fit <-aareg(Surv(days_to_death) ~ treatment + sex + stage + day, data = df)

autoplot(aa_fit)
```









